network:
  input: 200
  output: 5

agent:
  action_size: 5
  learning_rate: 0.0001
  gamma: 0.99
  batch_size: 256
  target_update_rate: 20
  epsilon: 1.0
  epsilon_min: 0.1
  decay_rate: 0.999

training:
  episodes: 5000
  max_episode_length: 30 # Max episode length in seconds
  render: True

evaluation:
  episodes: 10
  max_episode_length: 60