network:
  input: 33
  output: 40

agent:
  action_size: 40
  learning_rate: 0.00001 # -> 0.00001
  weight_decay: 0.0001
  gamma: 0.99
  batch_size: 128
  replay_buffer_size: 50000
  min_buffer_before_training: 500
  target_update_rate: 7
  epsilon: 1
  epsilon_min: 0.001
  decay_rate: 0.999
  lr_scheduler:
    gamma: 0.5
    step_size: 350
    lr_end: 0.00001

training:
  episodes: 10000
  max_episode_length: 30 # Max episode length in seconds
  render: False

evaluation:
  episodes: 50
  max_episode_length: 60
  render: True