network:
  input: 15
  output: 40

agent:
  action_size: 40
  learning_rate: 0.0005 # -> 0.00001
  weight_decay: 0
  gamma: 0.99
  batch_size: 256
  replay_buffer_size: 100000
  min_buffer_before_training: 5000
  target_update_rate: 7
  epsilon: 1
  epsilon_min: 0.001
  decay_rate: 0.998
  max_grad_norm: 5.0

training:
  episodes: 3000
  max_episode_length: 30 # Max episode length in seconds
  render: False

evaluation:
  episodes: 50
  max_episode_length: 60
  model_path: results/models/2025090716/model_3000.pth
  render: True